### ISSUE TITLE
Error on running install.sh 

### ISSUE THREAD

**Issue by MohakChugh** [WayfireWM/wf-install#11]
While running the install script in the wf-install folder, I get the error at line 70: function: not found. I am new to linux and I am not sure what I'm doing wrong.
![Screenshot from 2020-04-05 04-01-26](https://user-images.githubusercontent.com/33135218/78462693-31ecff00-76f2-11ea-997b-317d35464e92.png)

**Comment by ammen99** [comment]
Hi, can you try running the script with `bash install.sh ...`?

**Comment by MohakChugh** [comment]
I tried it, it didnt work

**Comment by ammen99** [comment]
@MohakChugh The same error, or something else this time?

**Comment by ammen99** [comment]
Also try to `git apply` the following patch after downloading it: http://ix.io/2hje

**Comment by Tommy21st** [comment]
I am having the same issue, i don't have a clue where or how to apply this patch? I am not very familiar with Linux, i am using ubuntu focal.

**Comment by soreau** [comment]
@Tommy21st From the wf-install directory, run `curl http://ix.io/2hje | git apply`. If you don't see an error and `git diff` shows the patch, this means it applied correctly. After doing this, run wf-install.

**Comment by Tommy21st** [comment]
Applied patch, now i got another error, HEAD is now at e20701f view: add set_minimize_hint() (#504)
HEAD is now at 0ae02ab Add custom labels on launchers from cmd+icon combo (#51)
./install.sh: 114: meson: not found.

**Comment by ammen99** [comment]
You need `meson` for building Wayfire.
