### ISSUE TITLE
Subprojects gvc is buildable: NO

### ISSUE THREAD

**Issue by lensaj** [WayfireWM/wf-install#12]
|Run-time dependency alsa found: NO (tried pkgconfig and cmake)
|
|subprojects/gvc/meson.build:60:2 Exception: Dependency "alsa" not found, tried pkgconfig and cmake

Subprojects gvc is buildable: NO

meson.build:26:2 ERROR: Subproject "subprojects/gvc" disabled can't get_variable on it.

I am running it on debian( Elive ),
meson.build:60:2 is:
60      libgvc_deps += dependency('alsa')

what package should I install?
I have tried libalsaplayer-dev

Regards

Yep! I got it! It needed libalsa-ocaml-dev
Sorry

**Comment by soreau** [comment]
libasound2-dev

**Comment by lensaj** [comment]
> 
> 
> libasound2-dev

Thanks, it came by deps.

**Comment by ammen99** [comment]
Closing since seems you found it :)
