### ISSUE TITLE
List of dependencies?

### ISSUE THREAD

**Issue by edent** [WayfireWM/wf-install#19]
When following the install instructions, I get the error: `./install.sh: line 114: meson: command not found`

I assume I have to `apt install meson`?

Would it be possible to get a list of dependencies added to the README? Or to have the script check before running?

**Comment by edent** [comment]
Next error was 
`meson.build:18:0: ERROR: Dependency "wayland-server" not found, tried pkgconfig and cmake`

But I already have `libwayland-server0 (1.18.0-2~exp1.1)` installed.

**Comment by edent** [comment]
This gets me most of the way there:
```
sudo apt install libwayland-dev wayland-protocols libcairo2-dev libdrm-dev libegl1-mesa-dev libglm-dev libinput-dev libxkbcommon-dev  libgbm-dev libgtkmm-3.0-dev
```

But it fails saying `Dependency wf-config found: NO found 0.4.0 but need: '>=0.5.0'`

**Comment by soreau** [comment]
Some distributions split the development portions into separate packages, so you need the package ending in -dev. The package you have installed provides the runtime library. You can install meson with apt but not ninja. You can install these with pip3 as well and it will install latest versions to ~/.local/bin/. The last command adds this to your `$PATH`. You can install the dependencies on Ubuntu 20.04 this way:

```
sudo apt install git python3-pip pkg-config libwayland-dev autoconf libtool libffi-dev libxml2-dev libegl1-mesa-dev libgles2-mesa-dev libgbm-dev libinput-dev libxkbcommon-dev libpixman-1-dev xutils-dev xcb-proto python3-xcbgen libcairo2-dev libglm-dev libjpeg-dev libgtkmm-3.0-dev xwayland libdrm-dev libgirepository1.0-dev libsystemd-dev policykit-1 libx11-xcb-dev libxcb-xinput-dev libxcb-composite0-dev xwayland
pip3 install meson ninja
. ~/.profile
```

**Comment by edent** [comment]
Thanks - I've installed all of those, but it still fails with the wf-config dependency. I don't see a way to install that.

**Comment by soreau** [comment]
Can you join #wayfire on irc.freenode.net? I would be able to more easily help you there.
