### ISSUE TITLE
Install script doesn't work with 0.6.0

### ISSUE THREAD

**Issue by nwg-piotr** [WayfireWM/wf-install#21]
`./install.sh --prefix /opt/wayfire --stream 0.6.0` ends up in:

> Run-time dependency wf-config found: NO (tried cmake)
meson.build:20:0: ERROR: Invalid version of dependency, need 'wf-config' ['>=0.6.0'] found '0.5.0'.
A full log can be found at /home/piotr/Clones/wf-install/wf-shell/build/meson-logs/meson-log.txt

[meson-log.txt](https://gist.github.com/nwg-piotr/55a50d1c5ff30e3d41edb00cb2c8cf19)

`./install.sh --prefix /opt/wayfire --stream master` behaves the same way.

**Comment by ammen99** [comment]
Try with `-c` ?

EDIT: `-c` will delete everything and re-download the submodules which is needed. I ran the script locally in clean state and it worked.

**Comment by nwg-piotr** [comment]
Still the same result.

**Comment by ammen99** [comment]
Ah I see, the problem is in wf-shell. I will update it.

**Comment by nwg-piotr** [comment]
Thanks!

**Comment by ammen99** [comment]
Can you try the 0.6.0 stream with `-c`?

**Comment by nwg-piotr** [comment]
It worked.

![image](https://user-images.githubusercontent.com/20579136/98482815-2a4f8480-2204-11eb-8ae9-6caed051fbdc.png)
