### ISSUE TITLE
Problem with config files

### ISSUE THREAD

**Issue by nwg-piotr** [WayfireWM/wf-install#22]
Leaving my old .ini files results in `wcm` [memory dump](https://gist.github.com/nwg-piotr/b4618ea6070cc20e2cc7d85eb9c50a06). If I choose to create new ones, I'm ending in up something like this:

> Do you want to override the existing config file /home/piotr/.config/wayfire.ini [y/n]? y
Do you want to override the existing config file /home/piotr/.config/wf-shell.ini [y/n]? y
Do you want to install wayfire-plugins-extra? [y/n]? y
Cloning into 'wayfire-plugins-extra'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 411 (delta 21), reused 16 (delta 8), pack-reused 367
Receiving objects: 100% (411/411), 155.90 KiB | 862.00 KiB/s, done.
Resolving deltas: 100% (237/237), done.
error: pathspec 'origin/0.6.0' did not match any file(s) known to git

**Comment by ammen99** [comment]
Yeah sorry wcm and extra plugins habe not been released yet.

**Comment by nwg-piotr** [comment]
Oh, all right.

**Comment by ammen99** [comment]
They should work with master stream though.

**Comment by nwg-piotr** [comment]
They do. I restored my old wayfire.ini and it didn't crash wcm.

**Comment by nwg-piotr** [comment]
It seems to be OK now.
