### ISSUE TITLE
install.sh assumes .config to exist

### ISSUE THREAD

**Issue by erikvanhamme** [WayfireWM/wf-install#3]
Tested on minimal system.

~/.config does not exist.

Script crashes with:
cp: cannot create regular file '/home/rsq/.config/wayfire.ini': No such file or directory

**Comment by erikvanhamme** [comment]
Did mkdir ~/.config and started script again.

Completed successfully this time, so a non-braindead user can at least recover from it.

**Comment by ammen99** [comment]
Does http://ix.io/2fxK fix the problem?

**Comment by erikvanhamme** [comment]
Yes, patch works.
