### ISSUE TITLE
Probably not a Problem just user error

### ISSUE THREAD

**Issue by Peng1029** [WayfireWM/wf-install#30]
The script is asking for the dependency wayland-server to install, however I can't figure out how to install it?
Oh I'm also on Ubuntu 21.04

**Comment by Javyre** [comment]
Maybe try this? https://packages.ubuntu.com/hirsute/libwayland-server0

**Comment by Peng1029** [comment]
Seems to be already Installed

**Comment by Peng1029** [comment]
Dependency wayland-server found: NO found 1.18.0 but need: '>=1.19' (cached)

**Comment by Peng1029** [comment]
Is there an unstable version of the repo with that version I can use?

**Comment by marcusbritanicus** [comment]
@Peng1029 You might wanna look into this: https://launchpad.net/~soreau/+archive/ubuntu/wayfirewm
Wayland 1.19 has just made it into Debian Sid. So it will take a while to percolate into Ubuntu. You might get it Ubuntu 21.10. Until then, you probably will be able to use @soreau's ppa.

**Comment by Peng1029** [comment]
Thanks this works, I've been trying to get this to work for weeks
