### ISSUE TITLE
ERROR: Neither a subproject directory nor a seatd.wrap file was found.

### ISSUE THREAD

**Issue by Slider-Override** [WayfireWM/wf-install#32]
Hi, Any Ides why it fail ?

./install.sh --prefix /opt/wayfire --stream 0.7.x
Building Wayfire 0.7.x
Installation prefix: /opt/wayfire
HEAD ist jetzt bei 61bcbec8 bump version to 0.7.3
HEAD ist jetzt bei fe91f18 bump version
The Meson build system
Version: 0.61.2
Source dir: /home/slider/Schreibtisch/wf-install/wayfire
Build dir: /home/slider/Schreibtisch/wf-install/wayfire/build
Build type: native build
Project name: wayfire
Project version: 0.7.3
C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
C linker for the host machine: cc ld.bfd 2.38
C++ compiler for the host machine: c++ (gcc 11.2.0 "c++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
C++ linker for the host machine: c++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency wayland-server found: YES 1.20.0
Run-time dependency wayland-client found: YES 1.20.0
Run-time dependency wayland-cursor found: YES 1.20.0
Run-time dependency wayland-protocols found: YES 1.25
Run-time dependency cairo found: YES 1.16.0
Run-time dependency pango found: YES 1.50.6
Run-time dependency pangocairo found: YES 1.50.6
Run-time dependency libdrm found: YES 2.4.110
Run-time dependency egl found: YES 1.5
Run-time dependency glesv2 found: YES 3.2
Run-time dependency glm found: YES 0.9.9.6
Run-time dependency libinput found: YES 1.20.0
Run-time dependency pixman-1 found: YES 0.40.0
Run-time dependency threads found: YES
Run-time dependency xkbcommon found: YES 1.4.0
Dependency wlroots skipped: feature use_system_wlroots disabled
Dependency wf-config skipped: feature use_system_wfconfig disabled

Executing subproject wlroots 

wlroots| Project name: wlroots
wlroots| Project version: 0.15.0
wlroots| C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
wlroots| C linker for the host machine: cc ld.bfd 2.38
wlroots| Compiler for C supports arguments -Wundef: YES
wlroots| Compiler for C supports arguments -Wlogical-op: YES
wlroots| Compiler for C supports arguments -Wmissing-include-dirs: YES
wlroots| Compiler for C supports arguments -Wold-style-definition: YES
wlroots| Compiler for C supports arguments -Wpointer-arith: YES
wlroots| Compiler for C supports arguments -Winit-self: YES
wlroots| Compiler for C supports arguments -Wstrict-prototypes: YES
wlroots| Compiler for C supports arguments -Wimplicit-fallthrough=2: YES
wlroots| Compiler for C supports arguments -Wendif-labels: YES
wlroots| Compiler for C supports arguments -Wstrict-aliasing=2: YES
wlroots| Compiler for C supports arguments -Woverflow: YES
wlroots| Compiler for C supports arguments -Wmissing-prototypes: YES
wlroots| Compiler for C supports arguments -Walloca: YES
wlroots| Compiler for C supports arguments -Wno-missing-braces: YES
wlroots| Compiler for C supports arguments -Wno-missing-field-initializers: YES
wlroots| Compiler for C supports arguments -Wno-unused-parameter: YES
wlroots| Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES
wlroots| Dependency wayland-server found: YES 1.20.0 (cached)
wlroots| Dependency libdrm found: YES 2.4.110 (cached)
wlroots| Run-time dependency gbm found: YES 22.0.1
wlroots| Dependency xkbcommon found: YES 1.4.0 (cached)
wlroots| Run-time dependency libudev found: YES 249
wlroots| Dependency pixman-1 found: YES 0.40.0 (cached)
wlroots| Library m found: YES
wlroots| Library rt found: YES
wlroots| Dependency wayland-protocols found: YES 1.25 (cached)
wlroots| Found pkg-config: /usr/bin/pkg-config (0.29.2)
wlroots| Build-time dependency wayland-scanner found: YES 1.20.0
wlroots| Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
wlroots| Dependency egl found: YES 1.5 (cached)
wlroots| Dependency glesv2 found: YES 3.2 (cached)
wlroots| Run-time dependency vulkan found: NO (tried pkgconfig and system)
wlroots| Message: Required for vulkan renderer support.
wlroots| Message: Required for vulkan renderer support.
wlroots| Dependency pixman-1 found: YES 0.40.0 (cached)
wlroots| Checking for function "gbm_bo_get_fd_for_plane" with dependency gbm: YES
wlroots| Dependency libinput found: YES 1.20.0 (cached)
wlroots| Run-time dependency xcb found: YES 1.14
wlroots| Found CMake: /usr/bin/cmake (3.22.1)
wlroots| WARNING: CMake Toolchain: Failed to determine CMake compilers state
wlroots| Run-time dependency xcb-dri3 found: NO (tried pkgconfig and cmake)
wlroots| Message: Required for X11 backend support.
wlroots| Message: Required for X11 backend support.
wlroots| Dependency wayland-client found: YES 1.20.0 (cached)
wlroots| Run-time dependency libseat found: NO (tried pkgconfig and cmake)
wlroots| Looking for a fallback subproject for the dependency libseat

subprojects/wlroots/backend/session/meson.build:1:0: ERROR: Neither a subproject directory nor a seatd.wrap file was found.

A full log can be found at /home/slider/Schreibtisch/wf-install/wayfire/build/meson-logs/meson-log.txt

---------------------------------------END OF--LOG------------------------------------
env[PKG_CONFIG_ALLOW_SYSTEM_LIBS]: 1
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --libs xcb` -> 0
-L/usr/lib/x86_64-linux-gnu -lxcb
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --libs xcb` -> 0
-lxcb
Run-time dependency xcb found: YES 1.14
Pkg-config binary for 1 is cached.
Determining dependency 'xcb-dri3' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --modversion xcb-dri3` -> 1

CMake binary for 1 is not cached
CMake binary missing from cross or native file, or env var undefined.
Trying a default CMake fallback at cmake
Found CMake: /usr/bin/cmake (3.22.1)
Extracting basic cmake information
CMake Toolchain: Calling CMake once to generate the compiler state
Calling CMake (['/usr/bin/cmake']) in /home/slider/Schreibtisch/wf-install/wayfire/build/meson-private/__CMake_compiler_info__ with:
  - "--trace-expand"
  - "--trace-format=json-v1"
  - "--no-warn-unused-cli"
  - "--trace-redirect=cmake_trace.txt"
  - "-G"
  - "Ninja"
  - "-DCMAKE_TOOLCHAIN_FILE=/home/slider/Schreibtisch/wf-install/wayfire/build/meson-private/__CMake_compiler_info__/CMakeMesonTempToolchainFile.cmake"
  - "."
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Try CMake generator: auto
Calling CMake (['/usr/bin/cmake']) in /home/slider/Schreibtisch/wf-install/wayfire/build/meson-private/cmake_xcb-dri3 with:
  - "--trace-expand"
  - "--trace-format=json-v1"
  - "--no-warn-unused-cli"
  - "--trace-redirect=cmake_trace.txt"
  - "-DCMAKE_TOOLCHAIN_FILE=/home/slider/Schreibtisch/wf-install/wayfire/build/meson-private/cmake_xcb-dri3/CMakeMesonToolchainFile.cmake"
  - "."
  -- Module search paths:    ['/', '/opt', '/usr', '/usr/local']
  -- CMake root:             /usr/share/cmake-3.22
  -- CMake architectures:    ['x86_64-linux-gnu']
  -- CMake lib search paths: ['lib', 'lib32', 'lib64', 'libx32', 'share', 'lib/x86_64-linux-gnu']
Preliminary CMake check failed. Aborting.
Run-time dependency xcb-dri3 found: NO (tried pkgconfig and cmake)
Message: Required for X11 backend support.
Message: Required for X11 backend support.
Dependency wayland-client found: YES 1.20.0 (cached)
Pkg-config binary for 1 is cached.
Determining dependency 'libseat' with pkg-config executable '/usr/bin/pkg-config'
env[PKG_CONFIG_PATH]: 
Called `/usr/bin/pkg-config --modversion libseat` -> 1

CMake binary for 1 is cached.
Preliminary CMake check failed. Aborting.
Run-time dependency libseat found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libseat

**Comment by ammen99** [comment]
You need to install libseat.

**Comment by Slider-Override** [comment]
i checked on this, but did not fine any manual for this on Ubuntu :-/

**Comment by Slider-Override** [comment]
got it http://in.archive.ubuntu.com/pool/universe/s/seatd/

thanks

**Comment by ammen99** [comment]
Nice! Closing this isssue since you have solved your problem.
