### ISSUE TITLE
wlroots| Dependency wayland-server found: NO found 1.18.0 but need: '>=1.20' (cached)

### ISSUE THREAD

**Issue by Emppu45** [WayfireWM/wf-install#33]
I tried updating with sudo apt update && sudo apt upgrade -y but that didn't help. How could I fix this issue?
[meson-log.txt](https://github.com/WayfireWM/wf-install/files/8597842/meson-log.txt)

**Comment by ammen99** [comment]
You need to install the latest wayland-server version from scratch. Wlroots requires it, so we can't do anything about it :/
