### ISSUE TITLE
How to Install on Ubuntu Jammy?

### ISSUE THREAD

**Issue by arjuna-dev** [WayfireWM/wf-install#37]
I recenlty installed linux version:

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

After installing dependencies I get:

`wlroots| Dependency wayland-server found: NO found 1.20.0 but need: '>=1.22' (cached)

subprojects/wlroots/meson.build:105:0: ERROR: Dependency 'wayland-server' is required but not found.

A full log can be found at /home/arjuna/Applications/wf-install/wayfire/build/meson-logs/meson-log.txt
`

Which seems to be the latest version available:

`arjuna@flubi:~/Applications/wf-install$ apt-cache policy libwayland-server0
libwayland-server0:
  Installed: 1.20.0-1ubuntu0.1
  Candidate: 1.20.0-1ubuntu0.1
  Version table:
 *** 1.20.0-1ubuntu0.1 500
        500 http://de.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.20.0-1 500
        500 http://de.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
`

But maybe I am missing something trivial or there is an easy fix? Maybe an Ubuntu upgrade or getting the library elsewehre?

**Comment by soreau** [comment]
You will have to install the dependencies you need. You can install them to /opt/wayfire and then set `PKG_CONFIG_PATH` to '/opt/wayfire/lib/x86_64-linux-gnu/pkgconfig:/opt/wayfire/share/pkgconfig' when running `install.sh`. You probably will need wayland and wayland-protocols from gitlab and possibly more for wlroots drm backend.
