### ISSUE TITLE
Dependencies different?

### ISSUE THREAD

**Issue by randompersonperson** [WayfireWM/wf-install#39]
In the install readme, there is two dependencies sections and they're different. The last three or four items are different. Which one is real??

Dependencies

The following is a list of dependencies needed on Ubuntu, similar lists are required on other distributions. The last one is only needed if you want to install WCM.

sudo apt install git meson python3-pip pkg-config libwayland-dev autoconf libtool libffi-dev libxml2-dev libegl1-mesa-dev libgles2-mesa-dev libgbm-dev libinput-dev libxkbcommon-dev libpixman-1-dev xutils-dev xcb-proto python3-xcbgen libcairo2-dev libglm-dev libjpeg-dev libgtkmm-3.0-dev xwayland libdrm-dev libgirepository1.0-dev libsystemd-dev policykit-1 libx11-xcb-dev libxcb-xinput-dev libxcb-composite0-dev xwayland libasound2-dev libpulse-dev libseat-dev valac libdbusmenu-gtk3-dev libxkbregistry-dev
install.sh

The general usage is:

git clone https://github.com/WayfireWM/wf-install
cd wf-install

./install.sh --prefix /opt/wayfire --stream 0.8.x

The last script will download all necessary components and install them to the given prefix. If you want to build the latest versions, use --stream master. For Wayfire and wf-shell, default configuration files will also be installed to $XDG_CONFIG_HOME/wayfire.ini or ~/.config/wayfire.ini

The script also has a few other options, which you can see by calling ./install.sh --help
Dependencies

The following is a list of dependencies needed on Ubuntu, similar lists are required on other distributions.

sudo apt install git meson python3-pip pkg-config libwayland-dev autoconf libtool libffi-dev libxml2-dev libegl1-mesa-dev libgles2-mesa-dev libgbm-dev libinput-dev libxkbcommon-dev libpixman-1-dev xutils-dev xcb-proto python3-xcbgen libcairo2-dev libglm-dev libjpeg-dev libgtkmm-3.0-dev xwayland libdrm-dev libgirepository1.0-dev libsystemd-dev policykit-1 libx11-xcb-dev libxcb-xinput-dev libxcb-composite0-dev xwayland libasound2-dev libpulse-dev libdisplay-info-dev hwdata

**Comment by ammen99** [comment]
Nice catch, I hadn't seen that we have two lists .. looking at the deps, I think you need all the dependencies from both lists.

**Comment by randompersonperson** [comment]
> Nice catch, I hadn't seen that we have two lists .. looking at the deps, I think you need all the dependencies from both lists.

i made pull request to fix it
