### ISSUE TITLE
Can't suppress the cache for rerunning a failed installation

### ISSUE THREAD

**Issue by vdegenne** [WayfireWM/wf-install#41]
I try to build `wayfire` from the master branch using this convenient script however during the first run I got this error:
![image](https://github.com/WayfireWM/wf-install/assets/2827383/ca609a7e-0ce9-4bb6-883d-1d1e678ff7e9)
From the error I understand I need wayland-protocols >= 1.32 but It seems I'm on 1.24 only, so I installed wayland-protocols 1.34 on my system and tried to run the script again, but as you can see from the capture everything is cache and the installation process still think I am using wayland-protocols `1.24` which now I know is not true. I can't find a way to reset the cache, I tried to delete the repository and clone again but the error is there again. 
I'm not familiar with `meson`, `wlroots` or whatever cause this error to persist.
I'm looking for your help, thanks

**Comment by ammen99** [comment]
Try adding the `-c` flag when running wf-install, it will remove everything from previous build attempts.

**Comment by ammen99** [comment]
Also it is possible that the caching happens because wayfire first checked for wayland-protocols and then the subproject wlroots also does the same ...

**Comment by vdegenne** [comment]
> Try adding the `-c` flag when running wf-install, it will remove everything from previous build attempts.

Yes I tried the `-c` flag before but it doesn't change anything.
I found out the reason I had a pkgconfig file at `/usr/local/share/pkgconfig/wayland-protocols.pc` which was seen as a cache file. I temporarily renamed this file and could advance to the next error of the build.

**Comment by ammen99** [comment]
Alright, I hope you figure it out :) I will close this issue for now since I don't think there is anything wf-install can do.
