### ISSUE TITLE
error on wayland-server.h

### ISSUE THREAD

**Issue by Ryuuusuke** [WayfireWM/wf-install#47]
I'm running on openSUSE tumbleweed and installed the dependencies.
when i ran `./install.sh --prefix /opt/wayfire --stream master` it gives me this output
am I missing something?

```
FAILED: test/misc/safe_list.p/safe-list-test.cpp.o 
c++ -Itest/misc/safe_list.p -Itest/misc -I../test/misc -I../src/api -I/usr/include/doctest -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -O2 -g '-DWAYFIRE_VERSION="0.10.0"' -DWLR_USE_UNSTABLE -fno-gnu-unique -Wno-unused-parameter -DWF_USE_CONFIG_H -MD -MQ test/misc/safe_list.p/safe-list-test.cpp.o -MF test/misc/safe_list.p/safe-list-test.cpp.o.d -o test/misc/safe_list.p/safe-list-test.cpp.o -c ../test/misc/safe-list-test.cpp
In file included from ../src/api/wayfire/nonstd/safe-list.hpp:12,
                 from ../test/misc/safe-list-test.cpp:4:
../src/api/wayfire/util.hpp:5:10: fatal error: wayland-server.h: No such file or directory
    5 | #include <wayland-server.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
[763/827] Compiling C++ object plugins/ipc-rules/libipc-rules.so.p/ipc-rules.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by soreau** [comment]
Can you try `./install.sh -c` without any other arguments? It will re-download the code and start fresh.

**Comment by Ryuuusuke** [comment]
> Can you try `./install.sh -c` without any other arguments? It will re-download the code and start fresh.

hello thank you for replying!

i tried add -c to clean install but it still gives me the same error output at the end

**Comment by soreau** [comment]
Does `wayland-server.h` exist in `/usr/include/`? If not, you might need to install whatever package provides this file.

**Comment by Ryuuusuke** [comment]
> Does `wayland-server.h` exist in `/usr/include/`? If not, you might need to install whatever package provides this file.

hello soreau!
i found that fedora has this package and including the wayland-server.h! https://packages.fedoraproject.org/pkgs/wayland/wayland-devel/fedora-rawhide.html
so i installed wayland
development package in opensuse and now its working! thank you for your time!
