### ISSUE TITLE
No session entry for SDDM. 

### ISSUE THREAD

**Issue by jumpinggoofballs** [WayfireWM/wf-install#6]
Cloned repo, ran the script, manually installed gobject-introspection to meet the depenendencies (that might also need to be fixed somehow), restarted and... Nothing. No session option to use Wayfire.

This is for SDDM on Arch. The AUR package does generate the session entry properly, and works.

**Comment by ammen99** [comment]
A good point, we have a .desktop entry in Wayfire which could be installed.

This of course is a little difficult when installing to a different prefix. If the prefix is not `/usr`, then the installed .desktop file won't be picked up by SDDM.

Anyway, we could explicitly ask during the installation whether to install to the `/usr/share/wayland-sessions` folder, which I think should be good enough.

**Comment by jumpinggoofballs** [comment]
Either the option to install to `/usr`; or even just the option to have a symbolic link in `/usr/share/wayland-sessions` to the necessary stuff in `/opt`.

**Comment by jumpinggoofballs** [comment]
Btw, the following `.desktop` entry works for SDDM:

`/usr/share/wayland-sessions/wayfire.desktop`
```
[Desktop Entry]
Exec=/opt/wayfire/bin/startwayfire
DesktopNames=Wayfire
Name=Wayfire
```

So just a matter of adding a question to the script as to whether to echo that text to the right location.

**Comment by ammen99** [comment]
We just added an entry in the installation script: #10
