### ISSUE TITLE
Binaries not added to PATH.

### ISSUE THREAD

**Issue by jumpinggoofballs** [WayfireWM/wf-install#7]
The script pulls down and installs the various packages to `/opt`, but then these are not added to any PATH so as to be accessible to the shell. 

This is on Arch Linux. When installed from the AUR, things work.

**Comment by ammen99** [comment]
The whole point is that you get a script startwayfire that you can run, and the location path is printed somewhere during the script. If you want to uninstall Wayfire, you can just remote the `/opt/wayfire` folder and that's it, there is nothing else you have installed. If you want to install to /usr, you can add `--prefix=/usr` which will install to your PATH.

TL;DR: the goal is to have everything installed at a single prefix, not to put files in many different locations.

**Comment by soreau** [comment]
You can copy startwayfire script from /opt to a place in PATH like /usr/local/bin/ and it should work.

**Comment by jumpinggoofballs** [comment]
Okay, this works. 

Miiiight be a good idea to mention this in the README of this repo.
